### ISSUE TITLE
Character encoding issues

### ISSUE THREAD

**Issue by billerby** [sciurius/chordpro#8]
Hi!

Seems like support for different charsets is missing? Trying to convert the attached file with swedish characters and the accented characters all gets replaced with question marks. Tried with the cho-file saved in both UTF-8 and in ISO8859-1 (which is the whats used for swedish). 

Also tried the --encoding=ENC command line argument with different encodings and different encodings of the input file:

chordpro allting-flyter.cho -o allting-flyter.pdf -encoding=UTF-8

chordpro allting-flyter.cho -o allting-flyter.pdf -encoding=ISO-8859-1

After conversion the file is encoded in UTF-32BE for some reason. Attaching the file saved in ISO-8859-1. (Had to zip it to be able to attach it).
[allting-flyter.cho.gz](https://github.com/sciurius/chordpro/files/850015/allting-flyter.cho.gz)

When using chordii I have to encode the input file in ISO-8859-1 to get the correct output.

Thanks!

**Comment by sciurius** [comment]
The attached file is encoded in ISO-8859-1, which is perfectly okay.
It turns out there was an (internal) encoding problem when using (built-in) corefonts like Times-Roman.
I've added a fix for that. Thanks for pointing this out.

As a workaround you can specify the filename of a TrueType font to use instead of the built-in corefont.

As for the --encoding option, you should not need it if the input data is Latin1 or UTF-8.
